[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#000000'
cursor = '#ffff00'

[colors.normal]
black = '#0e1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#ff00ff'
cyan = '#00ffff'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#ff22ff'
cyan = '#00ffff'
white = '#FFFFFF'
