#!/usr/bin/bash

echo '{"version":1}' # ig??
echo '['
echo '[]'

i3status | while :
do
    # following text is certainly code
    read line
    muted=""

    if [[ $(pactl get-source-mute @DEFAULT_SOURCE@ | rg "yes") ]];
    then
        muted="MUTED"
    fi

    line=",[{\"full_text\":\"$muted\",\"background\":\"#ff00ff\"},{\"full_text\":\"$line\"}]"
    echo "$line" || exit 1
done
